version: "3.8"

services:
  mongo:
    image: mongo:6
    container_name: job-tracker-mongo
    restart: unless-stopped
    volumes:
      - ./mongo-data:/data/db
    ports:
      - "27017:27017"

  backend:
    image: opt1mal04/job-application-tracker:backend
    container_name: job-tracker-backend
    restart: unless-stopped
    env_file:
      - ./backend/.env
    depends_on:
      - mongo
    ports:
      - "5000:5000"

  frontend:
    image: opt1mal04/job-application-tracker:frontend
    container_name: job-tracker-frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "3000:80"
